ДЗ номер 2 готова.
ikr0ni/go_level1 pull request #2
Opened 2021-11-22 20:27 UTC by ikr0ni

Без параметров выдает usage

2021-11-23 18:29 UTC, v-lozhkin requested changes

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +	length := math.Pow(float64(square), 2) / (4 * math.Pi)
Формулы не совсем корректные.

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +func calcSquare(top int, left int) int {
Лайк за использование функций

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +		{
Лайк за свитч, но фигурные скобки внутри кейсов не нужны

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +				fmt.Println("В числе", *number, "сотен", hundreds, "десятков", dozens, "единиц", units)
Вывод считывается странно %)
`В числе 999 сотен 9 десятков 9 единиц 9`
Сначала упорно не мог понять, откуда тут 999 сотен

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +	return square
Можно возвращщать сразу умножение, не обязательно складывать результат в переменную:
```go
return top * left
```

2021-11-23 18:29 UTC, v-lozhkin commented on lesson2/main.go
> +	units := ((number % 100) % 10)
Лишние внешние скобки

2021-11-23 20:08 UTC, ikr0ni commented on lesson2/main.go
> +	length := math.Pow(float64(square), 2) / (4 * math.Pi)
Исправлено в commit 142f56063391e0dd0f4b7bff0d259ae24eacb022

2021-11-23 20:08 UTC, ikr0ni commented on lesson2/main.go
> +		{
Исправлено в commit 142f56063391e0dd0f4b7bff0d259ae24eacb022

2021-11-23 20:08 UTC, ikr0ni commented on lesson2/main.go
> +				fmt.Println("В числе", *number, "сотен", hundreds, "десятков", dozens, "единиц", units)
Исправлено в commit 142f56063391e0dd0f4b7bff0d259ae24eacb022

2021-11-23 20:09 UTC, ikr0ni commented on lesson2/main.go
> +	return square
Исправлено в commit 142f56063391e0dd0f4b7bff0d259ae24eacb022

2021-11-23 20:09 UTC, ikr0ni commented on lesson2/main.go
> +	units := ((number % 100) % 10)
Исправлено в commit 142f56063391e0dd0f4b7bff0d259ae24eacb022

2021-11-24 07:31 UTC, v-lozhkin approved these changes
Все супер

2021-11-25 20:14 UTC, merged