ДЗ 4 ready
ikr0ni/go_level1 pull request #4
Opened 2021-11-29 16:58 UTC by ikr0ni

2021-12-02 19:11 UTC, v-lozhkin requested changes
Прикольно написано с точки зрения использования кучи языковых конструкций, но все же сильно раздуто, надо чутка причесать

2021-12-02 19:11 UTC, v-lozhkin commented on lesson4/main.go
> +func (a *ArrayToSort) GetUnsorted() {
GetUnsorted GetSorted выглядят прикольно, но абсолютно излишне с точки зрения гошного кода. 

К тому же еще и с указателями на входе. Сегодня как раз объяснял, почему так делать не нужно )

2021-12-02 19:11 UTC, v-lozhkin commented on lesson4/main.go
> +	copy(sort.sorted, sort.unsorted)
Хранить unsorted только чтобы скопировать его в sorted ?) 
Я, конечно, сегодня говорил, что не надо экономить на спичках, но это выглядит как то очень раздуто)

2021-12-02 19:11 UTC, v-lozhkin commented on lesson4/main.go
> +			temp := append(sort.sorted[:j-1], sort.sorted[j], sort.sorted[j-1])
Зачем таскать целые куски? Можно же просто свапнуть два элемента

2021-12-03 12:11 UTC, ikr0ni commented on lesson4/main.go
> +func (a *ArrayToSort) GetUnsorted() {
Да, конечно в методах Get использование поитеров не требуется, но как-то уже просто в привычку вошло, что если есть метод, то он что-то меняет внутри структуры, поправлю...

2021-12-03 12:23 UTC, ikr0ni commented on lesson4/main.go
> +			temp := append(sort.sorted[:j-1], sort.sorted[j], sort.sorted[j-1])
Да, что-то мне сходу непонравился reflect.Swapper, потому решил сам))), Исправил на swap

2021-12-03 12:25 UTC, ikr0ni commented on lesson4/main.go
> +	copy(sort.sorted, sort.unsorted)
По задумке, я его сделал, чтобы при необходимости можно было в любой момент вывести полученный исходно слайс.

2021-12-03 15:51 UTC, v-lozhkin commented on lesson4/main.go
> +			swap(j-1, j)
Не, не, не так :) 
sort.sorted[j-1], sort.sorted[j] = sort.sorted[j], sort.sorted[j-1]

2021-12-05 07:50 UTC, ikr0ni commented on lesson4/main.go
> +			swap(j-1, j)
Не, ну reflect.Swapper именно для этого сделан и работает)))

2021-12-05 13:23 UTC, v-lozhkin commented on lesson4/main.go
> +			swap(j-1, j)
reflect - вообще очень специфический пакет, который не нужно использовать без крайней необходимости. 
Как минимум, потому что он медленнее, чем обычные инструменты языка (можете провести замеры). 
Конечно, он позволяет решать некоторые проблемы, которые без него не решаются, и иногда просто необходим. Например, встроенные пакеты маршалинга/анмаршалинга структур в различные форматы (типа json) как раз таки и работают на рефлексии. 
Но конкретно в этом случае нет никакой необходимости в использовании рефликии. 
Подробнее о рефлексии в го можно почитать тут https://go.dev/blog/laws-of-reflection

2021-12-06 12:04 UTC, ikr0ni commented on lesson4/main.go
> +			swap(j-1, j)
Убрал рефлексию, хотя код с ней выглядит красивее, возможно тут как раз экономия на спичках)))

2021-12-06 12:05 UTC, ikr0ni commented on lesson4/main.go
> +func (a *ArrayToSort) GetUnsorted() {
указатели из Get методов изъяты

2021-12-06 12:08 UTC, v-lozhkin commented on lesson4/main.go
> +			swap(j-1, j)
Не вижу смысла спорить, потому что, конечно, решение всегда принимает разработчик. 
Просто приведу цитату с офсайта 
_It’s a powerful tool that should be used with care and avoided unless strictly necessary._

А по заданию - принято :)

2021-12-06 14:25 UTC, merged